export const languages = {
  en: {
    loginLabel: "Login",
    logoutLabel: "Logout",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    usernameLabel: "Username",
    signupText: "Don't have an account? Sign Up!",
    signupLabel: "Sign Up",
    commentCounterText: "comments",
    sendComment: "send comment",
    commentPlaceholder: "comment here"
    sortLabel: "Sort by",
    newest: "Newest",
    oldest: "Oldest",
    upvotes: "Most upvotes",
    downvotes: "Most downvotes",
    postedBy: "Posted by",
    now: "just now",
    minutes: "minutes ago",
    hour: "hour ago",
    hours: "hours ago",
    days: "days ago",
    weeks: "weeks ago",
    month: "month ago",
    months: "months ago",
    commentedBy: "Commented by",
  },
  pt: {
    loginLabel: "Entrar",
    logoutLabel: "Sair",
    emailLabel: "Endereço de Email",
    passwordLabel: "Palavra-chave",
    usernameLabel: "Nome de usuário",
    signupText: "Não tem uma conta? Cadastre-se!",
    signupLabel: "Cadastre-se",
    commentCounterText: "comentários",
    sendComment: "enviar comentário",
    commentPlaceholder: "comente aqui"
    sortLabel: "Ordenar por",
    newest: "Mais novos",
    oldest: "Mais antigos",
    upvotes: "Votos positivos",
    downvotes: "Votos negativos",
    postedBy: "Postado por",
    now: "agora há pouco",
    minutes: "minutos atrás",
    hour: "hora atrás",
    hours: "horas atrás",
    days: "dias atrás",
    weeks: "semanas atrás",
    month: "mês atrás",
    months: "meses atrás",
    commentedBy: "Comentado por",
  },
};
