export const languages = {
  en: {
    loginLabel: "Login",
    logoutLabel: "Logout",
    loginLinkText: "Already have an account? Sign in!",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    usernameLabel: "Username",
    signupText: "Don't have an account? Sign up!",
    signupLabel: "Sign Up",
    commentCounterText: "comments",
    sendComment: "Send comment",
    commentPlaceholder: "Comment here...",
    sortLabel: "Sort by",
    newest: "Newest",
    oldest: "Oldest",
    upvotes: "Most upvotes",
    downvotes: "Most downvotes",
    postedBy: "Posted by",
    now: "just now",
    minutes: "minutes ago",
    hour: "hour ago",
    hours: "hours ago",
    day: "day ago",
    days: "days ago",
    weeks: "weeks ago",
    month: "month ago",
    months: "months ago",
    commentedBy: "Commented by",
    postTitlePlaceholder: "Your post title",
    postTextPlaceholder: "Write your post here...",
    postButton: "Submit",
    postErrorAlert: "Something went wrong, please try again later",
    commentTextPlaceholder: "Write your comment here...",
    postFormLabel: "Submit a new text post:",
  },
  pt: {
    loginLabel: "Entrar",
    logoutLabel: "Sair",
    loginLinkText: "Já possui uma conta ? Faça login!",
    emailLabel: "Endereço de Email",
    passwordLabel: "Palavra-chave",
    usernameLabel: "Nome de usuário",
    signupText: "Não tem uma conta? Cadastre-se!",
    signupLabel: "Cadastre-se",
    commentCounterText: "comentários",
    sendComment: "Enviar comentário",
    commentPlaceholder: "Comente aqui...",
    sortLabel: "Ordenar por",
    newest: "Mais novos",
    oldest: "Mais antigos",
    upvotes: "Votos positivos",
    downvotes: "Votos negativos",
    postedBy: "Postado por",
    now: "agora há pouco",
    minutes: "minutos atrás",
    hour: "hora atrás",
    hours: "horas atrás",
    day: "dia atrás",
    days: "dias atrás",
    weeks: "semanas atrás",
    month: "mês atrás",
    months: "meses atrás",
    commentedBy: "Comentado por",
    postTitlePlaceholder: "Título da sua postagem",
    postTextPlaceholder: "Escreva sua postagem aqui...",
    postButton: "Enviar",
    postErrorAlert: "Algo deu errado, por favor tente novamente mais tarde",
    commentTextPlaceholder: "Escreva seu comentário aqui...",
    postFormLabel: "Enviar uma nova postagem de texto:",
  },
};
